using Test
using PureRNGs

include("philox.jl")
include("threefry.jl")
include("families.jl")
include("oracle_conformance.jl")
include("derive.jl")
include("bits.jl")
include("uniform.jl")
include("uniform_allocating.jl")
include("integers.jl")
include("range_allocating.jl")
include("device_base_seams.jl")
include("extension_metadata.jl")
include("normal.jl")
include("exponential.jl")
include("custom_axes.jl")
include("sampling.jl")
include("stateful.jl")
include("closed_audits.jl")
include("weighted_sampling.jl")
