name = "PureRNGs"
uuid = "2ccaadc3-3d9a-45d4-a2ec-95a2424790b7"
version = "0.1.0"
authors = ["Ben Cox <bcox@mpp.mpg.de>"]

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
PureRNGsAMDGPUExt = "AMDGPU"
PureRNGsCUDAExt = "CUDA"

[compat]
AMDGPU = "2"
CUDA = "5.8, 6"
KernelAbstractions = "0.9"
MLDataDevices = "1.17"
Random = "1"
Test = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
